### ISSUE TITLE
Jukebox Redux Store

### ISSUE THREAD

**Issue by IkeHunter** [ufosc/Jukebox-Frontend#108]
## Info

Information about the song queue and other song-related information is stored in "Jukeboxes" in the Jukebox Server backend. A data store needs to be created to handle an admin's available Jukeboxes, and provide information about the currently selected Jukebox. Each club has one jukebox, and jukeboxes will (as of right now) have the following structure from the backend API:

```json
{
    "name": "string",
    "clubId": "string",
    "spotifyLinks": [
      {
        "accessToken": "string",
        "userId": "string",
        "spotifyEmail": "string",
        "expiresIn": 0,
        "expiresAt": "2024-10-07T21:34:35.428Z",
        "tokenType": "string"
      }
    ],
    "activeSpotifyLink": {
      "accessToken": "string",
      "userId": "string",
      "spotifyEmail": "string",
      "expiresIn": 0,
      "expiresAt": "2024-10-07T21:34:35.428Z",
      "tokenType": "string"
    }
  }
```

A `SpotifyLink` contains information required for the app to connect to a user's spotify account.

At a minimum, the store should probably be structured like this:

```ts
type JukeboxState = {
  activeJukebox: Jukebox
  availableJukeboxes: Jukebox[]
}
```

It may also include stuff about currently playing tracks, etc, but that will probably be determined later.

## Task

- [x] Store all available jukeboxes
- [x] Store active jukebox
- [x] Set currently active jukebox
- [x] Select current spotify link (active link for active jukebox)
