### ISSUE TITLE
Create login page

### ISSUE THREAD

**Issue by IkeHunter** [ufosc/Jukebox-Frontend#11]
## Info

This page will just display a form that will allow users to log into the system. Since the API is not connected yet, just redirect to the '/' page.

It should contain the following fields:
- Email
- Password

## Tasks

- [ ] Create form component
- [ ] Create page, insert form
- [ ] Create function that prints "Logging in..." in console. This function will later be used to connect to the api. Remember to call `preventDefault` on the form so it doesn't submit a post request.
- [ ] Redirect to the '/' page.
- [ ] Route to the `/login` url

**Comment by KNPham1337** [comment]
I got this. Eventually, currently watching tutorials over weekend so hopefully I can start work next Monday 10/2
