### ISSUE TITLE
Create admin dashboard page

### ISSUE THREAD

**Issue by IkeHunter** [ufosc/Jukebox-Frontend#12]
## Info

This is just a simple task to simply create a directory and React component to house the dashboard. Connect it a router to show on `/dashboard`. This component will later be used to display a host of widgets for a club's admin.

## Task

- [ ] Create new directory for `Dashboard/`
- [ ] Create new component and css module for Dashboard
- [ ] Link to router with `/dashboard` url

**Comment by JonathanHooth** [comment]
I will handle this
