### ISSUE TITLE
Dashboard: Create member list component

### ISSUE THREAD

**Issue by IkeHunter** [ufosc/Jukebox-Frontend#14]
## Info

*Note: if a `members` state object has not been created yet to mimic the api, just create your own dummy data that can later be switched out for api data*

For the admin dashboard page, create a new member list component. This component should be reusable as it will be used on a separate members page. The list component should contain a list item component that takes in a member object as a prop. The structure will look similar to the following:

```jsx
// Remember, this will need to contain a for loop! You also don't have to use the same props structure shown here.
<MemberList>
   <MemberListItem member=${member} />
</MemberList>
```

The finished version will look different because you will need to loop over members and dynamically display a list item component for each member in the array (using a for loop in jsx). It is up to you how that for loop is implemented (using jsx, a js map function, etc).

## Tasks

- [ ] Create list component
- [ ] Create list item component
- [ ] In list component, iterate over members to display list item for each member
