### ISSUE TITLE
Create home page

### ISSUE THREAD

**Issue by IkeHunter** [ufosc/Jukebox-Frontend#18]
## Info

This page will more or less be a marketing page, and have information about the application. This page will be designed first in Figma then developed out according to the design.

## Tasks

- [ ] Design Figma page
- [ ] Develop page according to Figma
- [ ] Wire it up to the router
