### ISSUE TITLE
Public User Flow

### ISSUE THREAD

**Issue by IkeHunter** [ufosc/Jukebox-Frontend#27]
## Info

Make a flow chart, diagram, etc in Figma outlining how public/unauthenticated user would use/view the application.

## Tasks

- [ ] Queueing up song
- [ ] logging in
- [ ] seeing their data
- [ ] managing multiple groups
- [ ] etc...
