### ISSUE TITLE
Implement drag and drop for boards widgets

### ISSUE THREAD

**Issue by IkeHunter** [ufosc/Jukebox-Frontend#83]
## Info

Admins should be able to configure their own custom boards. Saving these boards will be configured in another task, this one is just focused on making the widgets draggable.

So far, the most popular library is [react-dnd](https://github.com/react-dnd/react-dnd?tab=readme-ov-file), and the smoothest is [@hello-pangea/dnd](https://github.com/hello-pangea/dnd?tab=readme-ov-file). Any other ideas are welcomed.

## Task

Primary goal:

- [ ] Admin should be able to create custom boards from a set of draggable widgets.

### Implementation Details

When converting the boards into draggable canvases, you can follow this as a guide, or ignore it:

- [ ] Swap the two panels on Boards 1, 2, and 3 (horizontally)
- [ ] Swap the currently playing and up next sections of the left section of boards 1, 2, 3 (vertically)
- [ ] Refactor the widgets to be represented by js objects, these objects will eventually be stored in the database to save board layouts. The type of object will ultimately depend on the library that you settle on

**Comment by c-schutz** [comment]
Can I have this issue?
