### ISSUE TITLE
Build out Registration Page

### ISSUE THREAD

**Issue by IkeHunter** [ufosc/Jukebox-Frontend#94]
## Info

The main goal is to just build out the registration form. The registration functionality from the server has not been connected to the frontend yet, but make sure that when it comes time to implement this feature it's relatively easy to hook it into the form. This means you'll need to make sure the form handles submit events and collects the form data. For now, this form data can just be logged to the console.

## Tasks

- [ ] Create register form
- [ ] Style page like figma
- [ ] Handle form submit (log to console)

## Resources

- [Design System](https://github.com/ufosc/Jukebox-Frontend/blob/main/docs/Design-System.md) - CSS variables, colors, fonts, etc
- [Contributing](https://github.com/ufosc/Jukebox-Frontend/blob/main/CONTRIBUTING.md)

## Prototypes

![Register Page - Light](https://github.com/user-attachments/assets/c31c68a9-1f56-4347-9803-6af420a96ba9)
![Register Page - Dark](https://github.com/user-attachments/assets/4f49b6ae-dc33-4f77-9074-84756d8db763)

**Comment by IkeHunter** [comment]
@rpa0309 For some reason it's not letting me assign you, but here's the registration task

**Comment by rpa0309** [comment]
Awesome thank you!

**Comment by kluan01** [comment]
I would love to do this :)

**Comment by sofijamitukevic** [comment]
Could I work on this for my college project

**Comment by IkeHunter** [comment]
@sofijamitukevic The UI for this component is already done, but there's an issue with the actual feature for registering a user. This issue should probably be closed. I can see if there's another issue you can use for the project, and I'll tag you in it.

**Comment by IkeHunter** [comment]
Just added a new issue "Build member detail page", you can try your hand at that one if you want.
